// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF1u0Mp9AJZPP1GQJNfIv0Kw99W7-ssUM',
    appId: '1:449687596316:web:439e55159dd4b2b6cd5ed9',
    messagingSenderId: '449687596316',
    projectId: 'db-gpdi-kaset-app',
    authDomain: 'db-gpdi-kaset-app.firebaseapp.com',
    storageBucket: 'db-gpdi-kaset-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEQAHZosudHd_J94E6OtndceHQGFqo_qs',
    appId: '1:449687596316:android:8d1680ae54159704cd5ed9',
    messagingSenderId: '449687596316',
    projectId: 'db-gpdi-kaset-app',
    storageBucket: 'db-gpdi-kaset-app.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCf622tMEP6smM5Y8qYIs_h6oC5DTL9fME',
    appId: '1:751540178046:web:b239becefd1fe85ec5dc2f',
    messagingSenderId: '751540178046',
    projectId: 'gpdi-kaset-flutter-app',
    authDomain: 'gpdi-kaset-flutter-app.firebaseapp.com',
    storageBucket: 'gpdi-kaset-flutter-app.appspot.com',
  );

}